card_locations = {
    ["Fissure"] = {"fissure", 667},
    ["Victory D."] = {"victoryd", 1446},
    ["Final Countdown"] = {"finalcountdown", 1384},
    ["Ojama Delta Hurricane!!"] = {"ojamadeltahurricane", 1425},
    ["Ojama Green"] = {"ojamagreen", 1358},
    ["Ojama Yellow"] = {"ojamayellow", 1399},
    ["Ojama Black"] = {"ojamablack", 1400},
    ["Hamon, Lord of Striking Thunder"] = {"hamon", 2013},
    ["Raviel, Lord of Phantasms"] = {"raviel", 2014},
    ["Uria, Lord of Searing Flames"] = {"uria", 2012},
    ["Huge Revolution"] = {"hugerevolution", 1245},
    ["Oppressed People"] = {"oppressedpeople", 1215},
    ["United Resistance"] = {"unitedresistance", 1216},
    ["People Running About"] = {"peoplerunningabout", 1214},
    ["Perfectly Ultimate Great Moth"] = {"perfectlyultimategreatmoth", 74},
    ["Petit Moth"] = {"petitmoth", 263},
    ["Cocoon of Evolution"] = {"cocoonofevolution", 79},
    ["Valkyrion the Magna Warrior"] = {"valkyrionthemagnawarrior", 798},
    ["Alpha The Magnet Warrior"] = {"alphathemagnetwarrior", 598},
    ["Beta The Magnet Warrior"] = {"betathemagnetwarrior", 617},
    ["Gamma The Magnet Warrior"] = {"gammathemagnetwarrior", 640},
    ["Dark Sage"] = {"darksage", 944},
    ["Dark Magician"] = {"darkmagician", 37},
    ["Time Wizard"] = {"timewizard", 16},
    ["Destiny Board"] = {"destinyboard", 939},
    ["Spirit Message 'I'"] = {"spiritmessagei", 981},
    ["Spirit Message 'N'"] = {"spiritmessagen", 982},
    ["Spirit Message 'A'"] = {"spiritmessagea", 983},
    ["Spirit Message 'L'"] = {"spiritmessagel", 984},
    ["X-Head Cannon"] = {"x-headcannon", 1159},
    ["Y-Dragon Head"] = {"y-dragonhead", 1200},
    ["Z-Metal Tank"] = {"z-metaltank", 1202},
    ["XY-Dragon Cannon"] = {"xy-dragoncannon", 1201},
    ["XZ-Tank Cannon"] = {"xz-tankcannon", 1253},
    ["YZ-Tank Dragon"] = {"yz-tankdragon", 1254},
    ["XYZ-Dragon Cannon"] = {"xyz-dragoncannon", 1203},
    ["V-Tiger Jet"] = {"v-tigerjet", 1944},
    ["W-Wing Catapult"] = {"w-wingcatapult", 1947},
    ["VW-Tiger Catapult"] = {"vw-tigercatapult", 1954},
    ["VWXYZ-Dragon Catapult Cannon"] = {"vwxyz-dragoncatapultcannon", 1955},
    ["Gate Guardian"] = {"gateguardian", 332},
    ["Kazejin"] = {"kazejin", 330},
    ["Suijin"] = {"suijin", 331},
    ["Sanga of the Thunder"] = {"sangaofthethunder", 329},
    ["Dark Scorpion Combination"] = {"darkscorpioncombination", 1390},
    ["Don Zaloog"] = {"donzaloog", 1111},
    ["Dark Scorpion - Chick the Yellow"] = {"darkscorpion-chicktheyellow", 1326},
    ["Dark Scorpion - Meanae the Thorn"] = {"darkscorpion-meanaethethorn", 1363},
    ["Dark Scorpion - Gorg the Strong"] = {"darkscorpion-gorgthestrong", 1362},
    ["Cliff the Trap Remover"] = {"cliffthetrapremover", 1282},
    ["Exodia the Forbidden One"] = {"exodiatheforbiddenone", 21},
    ["Left Arm of the Forbidden One"] = {"leftarmoftheforbiddenone", 20},
    ["Right Arm of the Forbidden One"] = {"rightarmoftheforbiddenone", 19},
    ["Left Leg of the Forbidden One"] = {"leftlegoftheforbiddenone", 18},
    ["Right Leg of the Forbidden One"] = {"rightlegoftheforbiddenone", 17},
    ["Max ATK Bonus 1"] = {"maxatkbonus1", 0},
    ["Max ATK Bonus 2"] = {"maxatkbonus2", 1},
    ["Max ATK Bonus 3"] = {"maxatkbonus3", 2},
    ["Max ATK Bonus 4"] = {"maxatkbonus4", 3},
    ["Max ATK Bonus 5"] = {"maxatkbonus5", 4},
    ["Max Damage Bonus 1"] = {"maxdamagebonus1", 5},
    ["Max Damage Bonus 2"] = {"maxdamagebonus2", 6},
    ["Max Damage Bonus 3"] = {"maxdamagebonus3", 7},
    ["Max Damage Bonus 4"] = {"maxdamagebonus4", 8},
    ["Max Damage Bonus 5"] = {"maxdamagebonus5", 9},
    ["Tribute Summon Bonus 1"] = {"tributesummonbonus1", 10},
    ["Tribute Summon Bonus 2"] = {"tributesummonbonus2", 11},
    ["Tribute Summon Bonus 3"] = {"tributesummonbonus3", 12},
    ["Tribute Summon Bonus 4"] = {"tributesummonbonus4", 13},
    ["Tribute Summon Bonus 5"] = {"tributesummonbonus5", 14},
    ["Fusion Summon Bonus 1"] = {"fusionsummonbonus1", 15},
    ["Fusion Summon Bonus 2"] = {"fusionsummonbonus2", 16},
    ["Fusion Summon Bonus 3"] = {"fusionsummonbonus3", 17},
    ["Fusion Summon Bonus 4"] = {"fusionsummonbonus4", 18},
    ["Fusion Summon Bonus 5"] = {"fusionsummonbonus5", 19},
    ["Fusion Summon Bonus 6"] = {"fusionsummonbonus6", 20},
    ["Fusion Summon Bonus 7"] = {"fusionsummonbonus7", 21},
    ["Fusion Summon Bonus 8"] = {"fusionsummonbonus8", 22},
    ["Fusion Summon Bonus 9"] = {"fusionsummonbonus9", 23},
    ["Fusion Summon Bonus 10"] = {"fusionsummonbonus10", 24},
    ["Fusion Summon Bonus 11"] = {"fusionsummonbonus11", 25},
    ["Fusion Summon Bonus 12"] = {"fusionsummonbonus12", 26},
    ["Ritual Summon Bonus 1"] = {"ritualsummonbonus1", 27},
    ["Ritual Summon Bonus 2"] = {"ritualsummonbonus2", 28},
    ["Ritual Summon Bonus 3"] = {"ritualsummonbonus3", 29},
    ["Ritual Summon Bonus 4"] = {"ritualsummonbonus4", 30},
    ["Ritual Summon Bonus 5"] = {"ritualsummonbonus5", 31},
    ["No Spell Cards Bonus 1"] = {"nospellcardsbonus1", 32},
    ["No Spell Cards Bonus 2"] = {"nospellcardsbonus2", 33},
    ["No Spell Cards Bonus 3"] = {"nospellcardsbonus3", 34},
    ["No Spell Cards Bonus 4"] = {"nospellcardsbonus4", 35},
    ["No Spell Cards Bonus 5"] = {"nospellcardsbonus5", 36},
    ["No Trap Cards Bonus 1"] = {"notrapcardsbonus1", 37},
    ["No Trap Cards Bonus 2"] = {"notrapcardsbonus2", 38},
    ["No Trap Cards Bonus 3"] = {"notrapcardsbonus3", 39},
    ["No Trap Cards Bonus 4"] = {"notrapcardsbonus4", 40},
    ["No Trap Cards Bonus 5"] = {"notrapcardsbonus5", 41},
    ["Over 20000 LP Bonus 1"] = {"over20000lpbonus1", 42},
    ["Over 20000 LP Bonus 2"] = {"over20000lpbonus2", 43},
    ["Over 20000 LP Bonus 3"] = {"over20000lpbonus3", 44},
    ["Over 20000 LP Bonus 4"] = {"over20000lpbonus4", 45},
    ["Over 20000 LP Bonus 5"] = {"over20000lpbonus5", 46},
    ["Over 20000 LP Bonus 6"] = {"over20000lpbonus6", 47},
    ["Over 20000 LP Bonus 7"] = {"over20000lpbonus7", 48},
    ["Over 20000 LP Bonus 8"] = {"over20000lpbonus8", 49},
    ["Over 20000 LP Bonus 9"] = {"over20000lpbonus9", 50},
    ["Low LP Bonus 1"] = {"lowlpbonus1", 51},
    ["Low LP Bonus 2"] = {"lowlpbonus2", 52},
    ["Low LP Bonus 3"] = {"lowlpbonus3", 53},
    ["Low LP Bonus 4"] = {"lowlpbonus4", 54},
    ["Low LP Bonus 5"] = {"lowlpbonus5", 55},
    ["Extremely Low LP Bonus 1"] = {"extremelylowlpbonus1", 56},
    ["Extremely Low LP Bonus 2"] = {"extremelylowlpbonus2", 57},
    ["Extremely Low LP Bonus 3"] = {"extremelylowlpbonus3", 58},
    ["Extremely Low LP Bonus 4"] = {"extremelylowlpbonus4", 59},
    ["Extremely Low LP Bonus 5"] = {"extremelylowlpbonus5", 60},
    ["Low Deck Bonus 1"] = {"lowdeckbonus1", 61},
    ["Low Deck Bonus 2"] = {"lowdeckbonus2", 62},
    ["Low Deck Bonus 3"] = {"lowdeckbonus3", 63},
    ["Low Deck Bonus 4"] = {"lowdeckbonus4", 64},
    ["Low Deck Bonus 5"] = {"lowdeckbonus5", 65},
    ["Extremely Low Deck Bonus 1"] = {"extremelylowdeckbonus1", 66},
    ["Extremely Low Deck Bonus 2"] = {"extremelylowdeckbonus2", 67},
    ["Extremely Low Deck Bonus 3"] = {"extremelylowdeckbonus3", 68},
    ["Extremely Low Deck Bonus 4"] = {"extremelylowdeckbonus4", 69},
    ["Extremely Low Deck Bonus 5"] = {"extremelylowdeckbonus5", 70},
    ["Effect Damage Only Bonus 1"] = {"effectdamageonlybonus1", 71},
    ["Effect Damage Only Bonus 2"] = {"effectdamageonlybonus2", 72},
    ["Effect Damage Only Bonus 3"] = {"effectdamageonlybonus3", 73},
    ["Effect Damage Only Bonus 4"] = {"effectdamageonlybonus4", 74},
    ["Effect Damage Only Bonus 5"] = {"effectdamageonlybonus5", 75},
    ["No More Cards Bonus 1"] = {"nomorecardsbonus1", 76},
    ["No More Cards Bonus 2"] = {"nomorecardsbonus2", 77},
    ["No More Cards Bonus 3"] = {"nomorecardsbonus3", 78},
    ["No More Cards Bonus 4"] = {"nomorecardsbonus4", 79},
    ["No More Cards Bonus 5"] = {"nomorecardsbonus5", 80},
    ["Opponent's Turn Finish Bonus 1"] = {"opponentsturnfinishbonus1", 81},
    ["Opponent's Turn Finish Bonus 2"] = {"opponentsturnfinishbonus2", 82},
    ["Opponent's Turn Finish Bonus 3"] = {"opponentsturnfinishbonus3", 83},
    ["Opponent's Turn Finish Bonus 4"] = {"opponentsturnfinishbonus4", 84},
    ["Opponent's Turn Finish Bonus 5"] = {"opponentsturnfinishbonus5", 85},
    ["Exodia Finish Bonus 1"] = {"exodiafinishbonus1", 86},
    ["Exodia Finish Bonus 2"] = {"exodiafinishbonus2", 87},
    ["Exodia Finish Bonus 3"] = {"exodiafinishbonus3", 88},
    ["Exodia Finish Bonus 4"] = {"exodiafinishbonus4", 89},
    ["Exodia Finish Bonus 5"] = {"exodiafinishbonus5", 90},
    ["Exodia Finish Bonus 6"] = {"exodiafinishbonus6", 91},
    ["Last Turn Finish Bonus 1"] = {"lastturnfinishbonus1", 92},
    ["Last Turn Finish Bonus 2"] = {"lastturnfinishbonus2", 93},
    ["Last Turn Finish Bonus 3"] = {"lastturnfinishbonus3", 94},
    ["Last Turn Finish Bonus 4"] = {"lastturnfinishbonus4", 95},
    ["Last Turn Finish Bonus 5"] = {"lastturnfinishbonus5", 96},
    ["Final Countdown Finish Bonus 1"] = {"finalcountdownfinishbonus1", 97},
    ["Final Countdown Finish Bonus 2"] = {"finalcountdownfinishbonus2", 98},
    ["Final Countdown Finish Bonus 3"] = {"finalcountdownfinishbonus3", 99},
    ["Final Countdown Finish Bonus 4"] = {"finalcountdownfinishbonus4", 100},
    ["Final Countdown Finish Bonus 5"] = {"finalcountdownfinishbonus5", 101},
    ["Destiny Board Finish Bonus 1"] = {"destinyboardfinishbonus1", 102},
    ["Destiny Board Finish Bonus 2"] = {"destinyboardfinishbonus2", 103},
    ["Destiny Board Finish Bonus 3"] = {"destinyboardfinishbonus3", 104},
    ["Destiny Board Finish Bonus 4"] = {"destinyboardfinishbonus4", 105},
    ["Destiny Board Finish Bonus 5"] = {"destinyboardfinishbonus5", 106},
    ["Destiny Board Finish Bonus 6"] = {"destinyboardfinishbonus6", 107},
    ["Destiny Board Finish Bonus 7"] = {"destinyboardfinishbonus7", 108},
    ["Destiny Board Finish Bonus 8"] = {"destinyboardfinishbonus8", 109},
    ["Destiny Board Finish Bonus 9"] = {"destinyboardfinishbonus9", 110},
    ["Destiny Board Finish Bonus 10"] = {"destinyboardfinishbonus10", 111},
    ["Yata-Garasu Finish Bonus 1"] = {"yata-garasufinishbonus1", 112},
    ["Yata-Garasu Finish Bonus 2"] = {"yata-garasufinishbonus2", 113},
    ["Yata-Garasu Finish Bonus 3"] = {"yata-garasufinishbonus3", 114},
    ["Yata-Garasu Finish Bonus 4"] = {"yata-garasufinishbonus4", 115},
    ["Yata-Garasu Finish Bonus 5"] = {"yata-garasufinishbonus5", 116},
    ["Skull Servant Finish Bonus 1"] = {"skullservantfinishbonus1", 117},
    ["Skull Servant Finish Bonus 2"] = {"skullservantfinishbonus2", 118},
    ["Skull Servant Finish Bonus 3"] = {"skullservantfinishbonus3", 119},
    ["Skull Servant Finish Bonus 4"] = {"skullservantfinishbonus4", 120},
    ["Skull Servant Finish Bonus 5"] = {"skullservantfinishbonus5", 121},
    ["Konami Bonus 1"] = {"konamibonus1", 122},
    ["Konami Bonus 2"] = {"konamibonus2", 123},
    ["Konami Bonus 3"] = {"konamibonus3", 124},
    ["Konami Bonus 4"] = {"konamibonus4", 125},
    ["Konami Bonus 5"] = {"konamibonus5", 126},
}

card_items = {}

function create_cards()
    for name, content in pairs(card_locations) do
        code = content[1]
        cid = content[2]
        table.insert(card_items, YuGiOhCard(name, code, cid))
    end
end

function find_card(cid)
    local cards = {}
    for _, card in ipairs(card_items) do
        if card:getCId() == cid then
            table.insert(cards, card)
        end
    end
    return cards
end

function find_card_by_code(code)
    for _, card in ipairs(card_items) do
        if card.code == code then
            return card
        end
    end
    return nil
end